################################### NETWORK ##################################
# network_mode
# 1: reactor, 2: ntyco, 3: io_uring
##############################################################################
port 8888
network_mode 1

################################# REPLICATION ################################
is_replication yes
master_ip 192.168.137.221
master_port 8888
is_slave no

is_rdma no
rdma_device rxe0
rdma_qp 4
rdma_num_chunks 1024
rdma_read_depth 128
rdma_internal_chunks 64
dump_raw_dir ./dump/dump_raw.dump

################################ LOG  ################################
#0: no; 1: info, debug, error; 2: debug, error; 3: error
log_level 1

################################ PERSISTENCE  ################################

# The filename where to dump the DB
dump_dir ./dump/dump.dump
# yes - aof, no - rdb
is_aof no
is_backup no

################################ MEMORY ######################################
max_memory 1073741824

init_dpdk ./pdb_dpdk.ini
dpdk_log ./log/dpdk_init.log
