################################### NETWORK ##################################
# network_mode
# 1: reactor, 2: ntyco, 3: io_uring
##############################################################################
port 8888
network_mode 1

################################# REPLICATION ################################
is_replication no
master_ip 192.168.137.222
master_port 8888


################################ PERSISTENCE  ################################

# The filename where to dump the DB
dump_dir ./dump/dump.dump
# yes - aof, no - rdb
is_aof yes

################################ MEMORY ######################################
max_memory 1073741824